markdown: kramdown
highlighter: none
permalink: pretty
encoding: utf-8
port: 4011
main_baseurl: https://bitwarden.com
destination: _site/help/api

sass:
  style: compressed

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - appveyor.yml
  - README.md

include: 
  - ".nojekyll"
